### ISSUE TITLE
Missing CSS File

### ISSUE THREAD

**Issue by heyimtyler99** [SniperGER/storeUI#1]
There’s no storeUI-1.0.css file anywhere.

**Comment by SniperGER** [comment]
I wasn't able to include the build instructions just yet.

Please run the following commands:
```
npm install
npm install -g grunt-cli
grunt build
```

The CSS file should be in /build/css/ afterwards.

**Comment by heyimtyler99** [comment]
i'm assuming i run it in the project folder?
